#ifndef GRAPHICS_8_DL_H
#define GRAPHICS_8_DL_H

#include <atari.h>

// Graphics 8 Display List
// 320x220 resolution (40 bytes per line)
// 4K Boundary Handling:
// Each 4K page can hold floor(4096 / 40) = 102 lines.
// 102 lines * 40 bytes = 4080 bytes.
// Remaining 16 bytes in 4K page are skipped.
// Block 1: 102 lines. Offset 0x0000.
// Block 2: 102 lines. Offset 0x1000.
// Block 3: 16 lines.  Offset 0x2000.
// Total: 220 lines.

void graphics_8_dl = {
    DL_BLK8,
    // Block 1: 102 lines
    DL_LMS(DL_GRAPHICS8), &framebuffer[0],
    DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, // 10
    DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, // 20
    DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, // 30
    DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, // 40
    DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, // 50
    DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, // 60
    DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, // 70
    DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, // 80
    DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, // 90
    DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, // 100
    DL_GRAPHICS8, // 101 (Total 102 with LMS)

    // Block 2: 102 lines
    DL_LMS(DL_GRAPHICS8), &framebuffer[0]+0x1000,
    DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, // 10
    DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, // 20
    DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, // 30
    DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, // 40
    DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, // 50
    DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, // 60
    DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, // 70
    DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, // 80
    DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, // 90
    DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, // 100
    DL_GRAPHICS8, // 101 (Total 102 with LMS)

    // Block 3: 16 lines
    DL_LMS(DL_GRAPHICS8), &framebuffer[0]+0x2000,
    DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, // 10
    DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, // 15 (Total 16 with LMS)

    DL_JVB, &graphics_8_dl
};

#endif // GRAPHICS_8_DL_H
